# Generated by Django 4.0.6 on 2023-08-31 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserManagment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='only_data_campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipient', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='ET')),
                ('Message', models.TextField(max_length=250)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SMS',
            },
        ),
        migrations.CreateModel(
            name='BulkSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phones', models.FileField(upload_to='UserManagment/uploads/Phones')),
                ('message', models.TextField()),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BulkSMS',
            },
        ),
        migrations.CreateModel(
            name='all_campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('date_tobe_sent', models.DateTimeField()),
                ('link', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('other', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField()),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UserManagment.services')),
            ],
            options={
                'db_table': 'all_campaigns',
            },
        ),
    ]
