# Generated by Django 4.0.6 on 2023-09-13 21:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SMS', '0002_all_campaigns_approved_all_campaigns_phones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_campaigns',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='only_data_campaigns',
            name='created_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2023, 9, 13, 21, 34, 7, 97263, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
    ]
