# Generated by Django 4.0.6 on 2023-12-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0004_only_data_campaigns_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='only_data_campaigns',
            name='app_models_user',
            field=models.PositiveBigIntegerField(blank=True, db_column='App\\Models\\User', null=True),
        ),
    ]
