# Generated by Django 4.0.6 on 2023-12-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0005_alter_only_data_campaigns_app_models_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_campaign_whitelist',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='all_campaigns',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
