# Generated by Django 4.0.6 on 2023-12-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0006_rename_customer_id_all_campaign_whitelist_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'templates',
            },
        ),
        migrations.AddField(
            model_name='all_campaign_whitelist',
            name='status',
            field=models.CharField(default='created', max_length=20),
        ),
        migrations.AddField(
            model_name='all_campaigns',
            name='status',
            field=models.CharField(default='created', max_length=20),
        ),
        migrations.AddField(
            model_name='only_data_campaigns',
            name='status',
            field=models.CharField(default='created', max_length=20),
        ),
    ]
