# Generated by Django 4.0.6 on 2023-12-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0007_template_all_campaign_whitelist_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_campaign_whitelist',
            name='age',
        ),
        migrations.RemoveField(
            model_name='all_campaign_whitelist',
            name='expected_delivery',
        ),
        migrations.RemoveField(
            model_name='only_data_campaigns',
            name='age',
        ),
        migrations.RemoveField(
            model_name='only_data_campaigns',
            name='expected_delivery',
        ),
        migrations.AddField(
            model_name='all_campaign_whitelist',
            name='maxage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='all_campaign_whitelist',
            name='maxsmsexpected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='all_campaign_whitelist',
            name='minage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='all_campaign_whitelist',
            name='minsmsexpected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='only_data_campaigns',
            name='maxage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='only_data_campaigns',
            name='maxsmsexpected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='only_data_campaigns',
            name='minage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='only_data_campaigns',
            name='minsmsexpected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_campaign_whitelist',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='all_campaign_whitelist',
            name='phone_type',
            field=models.CharField(blank=True, choices=[('smart', 'Smart Phone'), ('non-smart', 'non-smart Phone')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='only_data_campaigns',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='only_data_campaigns',
            name='phone_type',
            field=models.CharField(blank=True, choices=[('smart', 'Smart Phone'), ('non-smart', 'non-smart Phone')], max_length=15, null=True),
        ),
    ]
