# Generated by Django 4.0.6 on 2023-12-14 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0007_users_disabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SMS', '0008_remove_all_campaign_whitelist_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_campaign_whitelist',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='all_campaigns',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='only_data_campaigns',
            old_name='service_id',
            new_name='service',
        ),
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('link', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('phones', models.FileField(blank=True, null=True, upload_to='survey/Phones/')),
                ('message', models.TextField()),
                ('other', models.CharField(max_length=20)),
                ('minage', models.IntegerField(blank=True, null=True)),
                ('maxage', models.IntegerField(blank=True, null=True)),
                ('minsmsexpected', models.IntegerField(blank=True, null=True)),
                ('maxsmsexpected', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=15, null=True)),
                ('phone_type', models.CharField(blank=True, choices=[('smart', 'Smart Phone'), ('non-smart', 'non-smart Phone')], max_length=15, null=True)),
                ('date_tobe_sent', models.DateTimeField(null=True)),
                ('location', models.CharField(blank=True, max_length=191, null=True)),
                ('occupation', models.CharField(blank=True, max_length=191, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('status', models.CharField(default='created', max_length=20)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.services')),
            ],
            options={
                'db_table': 'survey',
            },
        ),
    ]
