# Generated by Django 4.0.6 on 2023-12-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0010_template_created_at_template_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_campaigns',
            name='link',
        ),
        migrations.RemoveField(
            model_name='all_campaigns',
            name='other',
        ),
    ]
