# Generated by Django 4.0.6 on 2023-12-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0011_remove_all_campaigns_link_remove_all_campaigns_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_campaigns',
            name='phones',
            field=models.FileField(blank=True, null=True, upload_to='content/Phones'),
        ),
    ]
