# Generated by Django 4.0.6 on 2023-12-15 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0012_alter_all_campaigns_phones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_campaign_whitelist',
            name='link',
        ),
        migrations.RemoveField(
            model_name='all_campaign_whitelist',
            name='other',
        ),
        migrations.RemoveField(
            model_name='all_campaign_whitelist',
            name='phones',
        ),
        migrations.AlterField(
            model_name='all_campaign_whitelist',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='all_campaign_whitelist',
            name='date_tobe_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='all_campaign_whitelist',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
