# Generated by Django 4.0.6 on 2023-12-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0014_remove_survey_link_remove_survey_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='only_data_campaigns',
            name='app_models_user',
        ),
    ]
