# Generated by Django 4.0.6 on 2023-12-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0015_remove_only_data_campaigns_app_models_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_campaigns',
            name='campaign_name',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='all_campaigns',
            name='ref_number',
            field=models.CharField(max_length=191, null=True),
        ),
    ]
