# Generated by Django 4.0.6 on 2023-12-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0016_all_campaigns_campaign_name_all_campaigns_ref_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_campaign_whitelist',
            name='campaign_name',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='all_campaign_whitelist',
            name='ref_number',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='campaign_name',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='ref_number',
            field=models.CharField(max_length=191, null=True),
        ),
    ]
