# Generated by Django 4.0.6 on 2023-12-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0017_all_campaign_whitelist_campaign_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='only_data_campaigns',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
