# Generated by Django 4.0.6 on 2023-12-15 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0013_customerfiles_created_at_customerfiles_updated_at_and_more'),
        ('SMS', '0018_only_data_campaigns_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='only_data_campaigns',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UserManagment.customers'),
        ),
    ]
