# Generated by Django 4.0.6 on 2023-12-15 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0013_customerfiles_created_at_customerfiles_updated_at_and_more'),
        ('SMS', '0019_alter_only_data_campaigns_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_campaign_whitelist',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.customers'),
        ),
        migrations.AlterField(
            model_name='all_campaigns',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.customers'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.customers'),
        ),
    ]
