# Generated by Django 4.0.6 on 2024-01-30 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0016_package_subscriptions_options'),
        ('SMS', '0021_smstype_all_campaign_whitelist_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_campaigns',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.customers'),
        ),
    ]
