# Generated by Django 4.0.6 on 2024-01-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0022_alter_all_campaigns_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_campaign_whitelist',
            name='type',
        ),
        migrations.RemoveField(
            model_name='all_campaigns',
            name='type',
        ),
        migrations.RemoveField(
            model_name='only_data_campaigns',
            name='type',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='type',
        ),
        migrations.DeleteModel(
            name='SMStype',
        ),
    ]
