# Generated by Django 4.0.6 on 2024-02-03 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0020_alter_category_subcategory_and_more'),
        ('SMS', '0024_remove_all_campaign_whitelist_maxage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='demographicsurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('campaign_name', models.CharField(max_length=191, null=True)),
                ('ref_number', models.CharField(max_length=191, null=True)),
                ('message', models.TextField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=15, null=True)),
                ('phone_type', models.CharField(blank=True, choices=[('smart', 'Smart Phone'), ('non-smart', 'non-smart Phone')], max_length=15, null=True)),
                ('date_tobe_sent', models.DateTimeField(null=True)),
                ('location', models.CharField(blank=True, max_length=191, null=True)),
                ('occupation', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('status', models.CharField(default='created', max_length=20)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.customers')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.services')),
            ],
            options={
                'db_table': 'demographicsurvey',
            },
        ),
        migrations.CreateModel(
            name='internalsurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('campaign_name', models.CharField(max_length=191, null=True)),
                ('ref_number', models.CharField(max_length=191, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('status', models.CharField(default='created', max_length=20)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.customers')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.services')),
            ],
            options={
                'db_table': 'internalsurvey',
            },
        ),
        migrations.CreateModel(
            name='ordinarysurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('phones', models.FileField(blank=True, null=True, upload_to='survey/Phones/')),
                ('campaign_name', models.CharField(max_length=191, null=True)),
                ('ref_number', models.CharField(max_length=191, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('status', models.CharField(default='created', max_length=20)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.customers')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.services')),
            ],
            options={
                'db_table': 'ordinarysurvey',
            },
        ),
        migrations.DeleteModel(
            name='survey',
        ),
    ]
