# Generated by Django 4.0.6 on 2024-02-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0025_demographicsurvey_internalsurvey_ordinarysurvey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulksms',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='creator',
        ),
    ]
