# Generated by Django 4.0.6 on 2024-02-16 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0023_location_region'),
        ('SMS', '0026_remove_bulksms_creator_remove_sms_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_campaign_whitelist',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='demographicsurvey',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='only_data_campaigns',
            name='occupation',
        ),
        migrations.AddField(
            model_name='all_campaign_whitelist',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.industries'),
        ),
        migrations.AddField(
            model_name='demographicsurvey',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.industries'),
        ),
        migrations.AddField(
            model_name='only_data_campaigns',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.industries'),
        ),
    ]
