# Generated by Django 4.0.6 on 2024-02-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0027_remove_all_campaign_whitelist_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinarysurvey',
            name='date_tobe_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicsurvey',
            name='date_tobe_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
