# Generated by Django 4.0.6 on 2024-02-16 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0023_location_region'),
        ('SMS', '0028_ordinarysurvey_date_tobe_sent_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='all_campaign_whitelist',
        #     name='location',
        # ),
        # migrations.RemoveField(
        #     model_name='demographicsurvey',
        #     name='location',
        # ),
        # migrations.RemoveField(
        #     model_name='only_data_campaigns',
        #     name='location',
        # ),
        migrations.AlterField(
            model_name='all_campaign_whitelist',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagment.industries'),
        ),
        migrations.AlterField(
            model_name='demographicsurvey',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagment.industries'),
        ),
        migrations.AlterField(
            model_name='only_data_campaigns',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagment.industries'),
        ),
    ]
