# Generated by Django 4.0.6 on 2024-02-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0032_all_campaign_whitelist_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographicsurvey',
            name='location',
        ),
    ]
