# Generated by Django 4.0.6 on 2024-02-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0023_location_region'),
        ('SMS', '0033_remove_demographicsurvey_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographicsurvey',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagment.location'),
        ),
    ]
