# Generated by Django 4.0.6 on 2024-02-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0034_demographicsurvey_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_campaign_whitelist',
            name='totalphones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='all_campaigns',
            name='totalphones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demographicsurvey',
            name='totalphones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalsurvey',
            name='totalphones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='only_data_campaigns',
            name='totalphones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordinarysurvey',
            name='totalphones',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
