# Generated by Django 4.0.6 on 2024-02-17 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0024_alter_location_customer'),
        ('SMS', '0037_wallet_checkoutdata_wallet_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalsurvey',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagment.industries'),
        ),
        migrations.AddField(
            model_name='internalsurvey',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagment.location'),
        ),
        migrations.AddField(
            model_name='ordinarysurvey',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagment.industries'),
        ),
        migrations.AddField(
            model_name='ordinarysurvey',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagment.location'),
        ),
    ]
