# Generated by Django 4.0.6 on 2023-09-12 09:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='business_type',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='company_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='company_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='ET'),
        ),
        migrations.AlterField(
            model_name='users',
            name='contact_person_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='contact_person_first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='contact_person_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='ET'),
        ),
        migrations.AlterField(
            model_name='users',
            name='employee_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='files',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='industry',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='usertype',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
