# Generated by Django 4.0.6 on 2023-12-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0003_alter_customer_contents_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_phones',
            name='name',
        ),
    ]
