# Generated by Django 4.0.6 on 2023-12-12 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0004_remove_customer_phones_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_phones',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_phonebook', to=settings.AUTH_USER_MODEL),
        ),
    ]
