# Generated by Django 4.0.6 on 2023-12-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0006_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
