# Generated by Django 4.0.6 on 2023-12-14 16:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('UserManagment', '0007_users_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='users',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='company_phone',
        ),
        migrations.RemoveField(
            model_name='users',
            name='contact_person_email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='contact_person_first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='contact_person_phone',
        ),
        migrations.RemoveField(
            model_name='users',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email_verified_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='employee_number',
        ),
        migrations.RemoveField(
            model_name='users',
            name='files',
        ),
        migrations.RemoveField(
            model_name='users',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='users',
            name='remember_token',
        ),
        migrations.RemoveField(
            model_name='users',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='usertype',
        ),
        migrations.AddField(
            model_name='users',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=30, null=True)),
                ('company_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='ET')),
                ('contact_person_first_name', models.CharField(max_length=20, null=True)),
                ('contact_person_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='ET')),
                ('contact_person_email', models.EmailField(max_length=254, null=True)),
                ('employee_number', models.IntegerField(null=True)),
                ('industry', models.CharField(blank=True, max_length=191, null=True)),
                ('business_type', models.CharField(blank=True, max_length=191, null=True)),
                ('usertype', models.CharField(max_length=30, null=True)),
                ('email_verified_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'customers',
            },
            bases=('UserManagment.users',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=191, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
            options={
                'db_table': 'staff',
            },
            bases=('UserManagment.users',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
