# Generated by Django 4.0.6 on 2023-12-15 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0009_users_created_at_users_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='industry',
        ),
        migrations.AddField(
            model_name='customers',
            name='bussiness_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.bussiness_types'),
        ),
        migrations.AddField(
            model_name='customers',
            name='industries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.industries'),
        ),
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services'),
        ),
        migrations.AddField(
            model_name='services',
            name='meta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='customerfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='customer/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_files',
            },
        ),
    ]
