# Generated by Django 4.0.6 on 2023-12-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0011_remove_customers_bussiness_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
