# Generated by Django 4.0.6 on 2023-12-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0014_customcategory_subcategories_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(null=True, to='UserManagment.subcategories'),
        ),
    ]
