# Generated by Django 4.0.6 on 2023-12-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0015_remove_category_subcategory_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_subscriptions',
            name='options',
            field=models.ManyToManyField(null=True, to='UserManagment.subcategories'),
        ),
    ]
