# Generated by Django 4.0.6 on 2024-02-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0016_package_subscriptions_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='industry',
        ),
    ]
