# Generated by Django 4.0.6 on 2024-02-01 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0017_remove_customers_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.bussiness_types'),
        ),
        migrations.AddField(
            model_name='customers',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='UserManagment.industries'),
        ),
    ]
