# Generated by Django 4.0.6 on 2024-02-14 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0020_alter_category_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('create', models.BooleanField(default=False)),
                ('view', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('finance', models.BooleanField(default=False)),
                ('content_editor', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagment.group'),
        ),
    ]
