# Generated by Django 4.0.6 on 2024-02-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0021_group_alter_staff_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='usertype',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
